version: "3.9"

networks: 
  emodim:
    name: emodim

services:
  tensorflow-serving:
    image: tensorflow/serving:latest
    container_name: sentence-analysis
    networks: 
      - emodim
    ports:
      - "8501:8501"
    volumes:
      - "./sentence-analysis/model/rnnmodel:/models/rnnmodel"
    environment: 
      - MODEL_NAME=rnnmodel
    command:
      - "--rest_api_enable_cors_support"
  word-analysis:
    container_name: word-analysis
    build:
      context: ./word-analysis
      dockerfile: Dockerfile
    networks: 
      - emodim
    ports:
      - "5000:5000"
    volumes:
      - "./skipgram_dbs:/app/skipgram_dbs"
#       - "D:\\Work\\skipgram_dbs:/app/skipgram_dbs"
  chat-server:
    container_name: chat-server
    build:
      context: ./chatServer
      dockerfile: Dockerfile
    networks: 
      - emodim
    ports:
      - "3010:3010"
    volumes:
      - "chatServer/logs:/app/logs"
  front:
    container_name: front
    build:
      context: ./emodim-front
      dockerfile: Dockerfile
    networks: 
      - emodim
    ports:
      - "3000:3000"
