version: "3.9"

networks: 
  emodim:
    name: emodim

services:
  tensorflow-serving:
    image: tensorflow/serving
    container_name: sentence-analyzer
    networks: 
      - emodim
    ports:
      - "8501:8501"
    volumes:
      -  "./classifier/model/rnnmodel:/models/rnnmodel"
    environment: 
      - MODEL_NAME=rnnmodel
  python-docker:
    container_name: word-analyzer
    build:
      context: ./python-docker
      dockerfile: Dockerfile
    networks: 
      - emodim
    ports:
      - "5000:5000"
    volumes:
      - "./skipgram_dbs:/app/skipgram_dbs"
  chat-server:
    container_name: chat-server
    build:
      context: ./chatServer
      dockerfile: Dockerfile
    networks: 
      - emodim
    ports:
      - "3010:3010"
  front:
    container_name: front
    build:
      context: ./emodim-front
      dockerfile: Dockerfile
    networks: 
      - emodim
    ports:
      - "3000:3000"